name: taskmanager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # -----------------------------
  # State Management
  # -----------------------------
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5

  # -----------------------------
  # Navigation
  # -----------------------------
  go_router: ^10.0.0

  # -----------------------------
  # UI & Design
  # -----------------------------
  flex_color_scheme: ^7.2.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  gap: ^3.0.1

  # -----------------------------
  # Utilities
  # -----------------------------
  intl: ^0.18.1
  path: ^1.8.3

  # -----------------------------
  # Local Database
  # -----------------------------
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
