name: taskmanager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # -----------------------------
  # State Management
  # -----------------------------
  flutter_riverpod: ^3.0.3
  equatable: ^2.0.6

  # -----------------------------
  # Navigation
  # -----------------------------
  go_router: ^17.0.1

  # -----------------------------
  # UI & Design
  # -----------------------------
  flex_color_scheme: ^8.4.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.3.3
  gap: ^3.0.1

  # -----------------------------
  # Utilities
  # -----------------------------
  intl: ^0.20.2
  path: ^1.8.3

  # -----------------------------
  # Local Database
  # -----------------------------
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
